# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-10 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captivitate', '0004_auto_20170610_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pseudo',
            new_name='username',
        ),
    ]
