# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-30 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captivitate', '0010_migrate_django_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.CharField(blank=True, help_text='Commentaire', max_length=255),
        ),
    ]
